/obj/item/clothing/head/modular/marine/old
	colorable_allowed = PRESET_COLORS_ALLOWED|HAIR_CONCEALING_CHANGE_ALLOWED
	attachments_allowed = list(
		/obj/item/armor_module/module/tyr_head,
		/obj/item/armor_module/module/hod_head,
		/obj/item/armor_module/module/mimir_environment_protection/mimir_helmet,
		/obj/item/armor_module/module/mimir_environment_protection/mimir_helmet/mark1,
		/obj/item/armor_module/module/sigyn_head,
		/obj/item/armor_module/module/welding,
		/obj/item/armor_module/module/welding/superior,
		/obj/item/armor_module/module/binoculars,
		/obj/item/armor_module/module/binoculars/artemis_mark_two,
		/obj/item/armor_module/module/artemis,
		/obj/item/armor_module/module/antenna,
		/obj/item/armor_module/module/night_vision,
		/obj/item/armor_module/storage/helmet,
		/obj/item/armor_module/armor/badge,
		/obj/item/armor_module/armor/visor/marine/old,
		/obj/item/armor_module/armor/visor/marine/old/skirmisher,
		/obj/item/armor_module/armor/visor/marine/old/scout,
		/obj/item/armor_module/armor/visor/marine/old/eva,
		/obj/item/armor_module/armor/visor/marine/old/eva/skull,
		/obj/item/armor_module/armor/visor/marine/old/eod,
		/obj/item/armor_module/armor/visor/marine/old/assault,
		/obj/item/armor_module/module/fire_proof_helmet,
		/obj/item/armor_module/module/motion_detector,
	)
